# Generated by Django 5.0.2 on 2025-09-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumupcheckout',
            name='checkout_id',
            field=models.CharField(blank=True, help_text='ID returned by SumUp (alternative name for compatibility)', max_length=255),
        ),
    ]
