# Generated by Django 5.0.2 on 2025-09-05 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_sumuppayment_artist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='currency',
            field=models.CharField(db_index=True, default='GBP', max_length=3),
        ),
        migrations.AlterField(
            model_name='sumupcheckout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='sumupcheckout',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='sumuptransaction',
            name='timestamp',
            field=models.DateTimeField(db_index=True, help_text='Transaction time from SumUp'),
        ),
        migrations.CreateModel(
            name='ArtistSumUpAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_type', models.CharField(default='Bearer', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('scope', models.CharField(blank=True, default='', max_length=255)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sumup', to='payments.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('amount_gbp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('status', models.CharField(default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='payments.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(default='sumup', max_length=20)),
                ('checkout_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('raw', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='payments.order')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_gbp', models.DecimalField(decimal_places=2, default=25.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('citypay_token', models.CharField(blank=True, default='', max_length=200)),
                ('sumup_token', models.CharField(blank=True, default='', max_length=200)),
                ('next_charge_date', models.DateField(blank=True, null=True)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='payments.artist')),
            ],
        ),
    ]
