# Generated by Django 5.0.2 on 2025-11-24 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_add_polling_fields'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sumupcheckout',
            name='order',
            field=models.ForeignKey(
                blank=True,
                help_text='Order for ticket purchases (null for standalone payments like listing fees)',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='checkouts',
                to='orders.order'
            ),
        ),
    ]
