# Generated by Django 5.0.2 on 2025-09-26 16:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingFeeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_fee', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Standard listing fee for events', max_digits=10)),
                ('premium_fee', models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Premium listing fee (e.g., featured events)', max_digits=10)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('require_payment_before_publish', models.BooleanField(default=True, help_text='Require listing fee payment before event can be published')),
                ('grace_period_hours', models.IntegerField(default=24, help_text='Hours to complete payment after event creation')),
                ('platform_name', models.CharField(default='Jersey Events', help_text='Platform name for payment descriptions', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Listing Fee Configuration',
                'verbose_name_plural': 'Listing Fee Configurations',
            },
        ),
        migrations.CreateModel(
            name='ListingFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Listing fee amount in GBP', max_digits=10)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('sumup_checkout_id', models.CharField(blank=True, help_text='SumUp checkout ID for tracking', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_data', models.JSONField(blank=True, default=dict, help_text='Store SumUp payment response data')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing_fee', to='events.event')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_fees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
