# Generated by Django 5.0.2 on 2025-09-26 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_listingfeeconfig_listingfee'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_validated',
            field=models.BooleanField(default=False, help_text='Whether this ticket has been used for entry'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Order this ticket belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='orders.order'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Generated PDF ticket file', null=True, upload_to='tickets/pdfs/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='qr_data',
            field=models.TextField(blank=True, help_text='QR code data for ticket validation'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='validated_at',
            field=models.DateTimeField(blank=True, help_text='When this ticket was validated for entry', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='validated_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who validated this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='validation_hash',
            field=models.CharField(blank=True, help_text='Unique validation hash for ticket verification', max_length=32),
        ),
    ]
