# Generated by Django 5.0.2 on 2025-10-09 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_ticket_is_validated_ticket_order_ticket_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='processing_fee_passed_to_customer',
            field=models.BooleanField(default=False, help_text='If True, the 1.69% SumUp processing fee is added to the ticket price for customers. If False, the organizer absorbs the processing fee.'),
        ),
        migrations.CreateModel(
            name='TicketTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_type', models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP'), ('child', 'Child'), ('concession', 'Concession'), ('elderly', 'Elderly/Senior'), ('student', 'Student'), ('group', 'Group'), ('earlybird', 'Early Bird')], default='standard', max_length=20)),
                ('name', models.CharField(help_text="Display name for this tier (e.g., 'VIP Access', 'General Admission')", max_length=100)),
                ('description', models.TextField(blank=True, help_text="Description of what's included in this tier")),
                ('price', models.DecimalField(decimal_places=2, help_text='Base price for this tier', max_digits=10)),
                ('quantity_available', models.PositiveIntegerField(help_text='Number of tickets available at this tier')),
                ('quantity_sold', models.PositiveIntegerField(default=0, help_text='Number of tickets sold at this tier')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tier is available for purchase')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('min_purchase', models.PositiveIntegerField(default=1, help_text='Minimum number of tickets per purchase')),
                ('max_purchase', models.PositiveIntegerField(default=10, help_text='Maximum number of tickets per purchase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_tiers', to='events.event')),
            ],
            options={
                'ordering': ['event', 'sort_order', 'tier_type'],
                'unique_together': {('event', 'tier_type')},
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_tier',
            field=models.ForeignKey(blank=True, help_text='Ticket tier (VIP, Standard, etc.). Null for legacy tickets.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='events.tickettier'),
        ),
    ]
