# Generated by Django 5.0.2 on 2025-09-25 20:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_migrate_existing_artists_to_sumup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyConnectionMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_artists', models.IntegerField(default=0)),
                ('connected_artists', models.IntegerField(default=0)),
                ('new_connections', models.IntegerField(default=0)),
                ('disconnections', models.IntegerField(default=0)),
                ('invitations_sent', models.IntegerField(default=0)),
                ('page_views', models.IntegerField(default=0)),
                ('oauth_starts', models.IntegerField(default=0)),
                ('oauth_completions', models.IntegerField(default=0)),
                ('oauth_failures', models.IntegerField(default=0)),
                ('connection_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
            ],
            options={
                'verbose_name': 'Daily Connection Metrics',
                'verbose_name_plural': 'Daily Connection Metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EmailCampaignMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.IntegerField(default=0)),
                ('successful_sends', models.IntegerField(default=0)),
                ('failed_sends', models.IntegerField(default=0)),
                ('opens', models.IntegerField(default=0)),
                ('unique_opens', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('unique_clicks', models.IntegerField(default=0)),
                ('oauth_starts', models.IntegerField(default=0)),
                ('oauth_completions', models.IntegerField(default=0)),
                ('open_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('click_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConnectionAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_rate', 'Low Connection Rate'), ('declining_rate', 'Declining Connection Rate'), ('stagnant_rate', 'Stagnant Connection Rate'), ('milestone_reached', 'Milestone Reached')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=10)),
                ('message', models.TextField()),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('initial_total_artists', models.IntegerField(default=0)),
                ('initial_connected_artists', models.IntegerField(default=0)),
                ('initial_connection_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('final_total_artists', models.IntegerField(default=0)),
                ('final_connected_artists', models.IntegerField(default=0)),
                ('final_connection_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('new_connections', models.IntegerField(default=0)),
                ('disconnections', models.IntegerField(default=0)),
                ('invitations_sent', models.IntegerField(default=0)),
                ('emails_opened', models.IntegerField(default=0)),
                ('links_clicked', models.IntegerField(default=0)),
                ('campaigns_sent', models.IntegerField(default=0)),
                ('average_open_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('average_click_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('average_conversion_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('key_insights', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('week_start', 'week_end')},
            },
        ),
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('bounced', models.BooleanField(default=False)),
                ('opened', models.BooleanField(default=False)),
                ('first_opened_at', models.DateTimeField(blank=True, null=True)),
                ('open_count', models.IntegerField(default=0)),
                ('clicked', models.BooleanField(default=False)),
                ('first_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('click_count', models.IntegerField(default=0)),
                ('oauth_started', models.BooleanField(default=False)),
                ('oauth_completed', models.BooleanField(default=False)),
                ('oauth_completed_at', models.DateTimeField(blank=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_emails', to='accounts.artistprofile')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='analytics.emailcampaignmetrics')),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('campaign', 'artist')},
            },
        ),
        migrations.CreateModel(
            name='SumUpConnectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('invited', 'Invitation Sent'), ('email_opened', 'Email Opened'), ('link_clicked', 'Link Clicked'), ('page_viewed', 'Connection Page Viewed'), ('oauth_started', 'OAuth Started'), ('oauth_completed', 'OAuth Completed'), ('oauth_failed', 'OAuth Failed'), ('disconnected', 'Disconnected')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_events', to='accounts.artistprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['artist', 'event_type'], name='analytics_s_artist__a5b07d_idx'), models.Index(fields=['created_at'], name='analytics_s_created_72f8a0_idx')],
            },
        ),
    ]
