# Generated by Django 5.0.2 on 2025-09-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
