# Generated by Django 5.0.2 on 2025-09-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='sumup_access_token',
            field=models.TextField(blank=True, help_text='SumUp OAuth access token for this artist'),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='sumup_connected_at',
            field=models.DateTimeField(blank=True, help_text='When SumUp was first connected', null=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='sumup_connection_status',
            field=models.CharField(choices=[('not_connected', 'Not Connected'), ('connected', 'Connected'), ('expired', 'Token Expired'), ('error', 'Connection Error')], default='not_connected', help_text='Current SumUp connection status', max_length=20),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='sumup_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the access token expires', null=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='sumup_merchant_code',
            field=models.CharField(blank=True, help_text="Artist's SumUp merchant code", max_length=50),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='sumup_refresh_token',
            field=models.TextField(blank=True, help_text='SumUp OAuth refresh token'),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='sumup_scope',
            field=models.CharField(blank=True, help_text='OAuth scopes granted', max_length=255),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='sumup_token_type',
            field=models.CharField(blank=True, default='Bearer', max_length=20),
        ),
    ]
