# Generated by Django 5.0.2 on 2025-09-25 15:19

from django.db import migrations


def migrate_existing_artists_to_sumup_workflow(apps, schema_editor):
    """
    Migrate existing artists to new SumUp OAuth workflow.

    This migration:
    1. Sets all existing artists to 'not_connected' status
    2. Provides migration guidance for existing SumUp connections
    3. Logs artists who need to reconnect their SumUp accounts
    """
    ArtistProfile = apps.get_model('accounts', 'ArtistProfile')

    # Get all existing artist profiles
    existing_artists = ArtistProfile.objects.all()

    if existing_artists.exists():
        print(f"\n🔄 Migrating {existing_artists.count()} existing artists to new SumUp OAuth workflow...")

        # Update all existing artists to not_connected status
        updated_count = existing_artists.update(
            sumup_connection_status='not_connected',
            sumup_access_token='',
            sumup_refresh_token='',
            sumup_token_type='',
            sumup_expires_at=None,
            sumup_scope='',
            sumup_merchant_code='',
            sumup_connected_at=None
        )

        print(f"✅ Updated {updated_count} artist profiles")

        # Log artists who were previously active
        active_artists = existing_artists.filter(is_approved=True)
        if active_artists.exists():
            print(f"\n📧 IMPORTANT: {active_artists.count()} approved artists need to reconnect SumUp:")
            for artist in active_artists[:10]:  # Show first 10
                print(f"  - {artist.display_name} ({artist.user.email})")

            if active_artists.count() > 10:
                print(f"  ... and {active_artists.count() - 10} more artists")

        print("\n" + "="*60)
        print("🔧 MIGRATION COMPLETED - NEXT STEPS:")
        print("="*60)
        print("1. Send email to all approved artists asking them to reconnect SumUp")
        print("2. Artists can reconnect at: /accounts/sumup/connect/")
        print("3. New payment flow will route directly to artist SumUp accounts")
        print("4. Platform commission will be tracked separately")
        print("="*60)
    else:
        print("✅ No existing artists to migrate")


def reverse_migration(apps, schema_editor):
    """Reverse migration - reset SumUp fields to default values."""
    ArtistProfile = apps.get_model('accounts', 'ArtistProfile')

    # Reset all SumUp fields to defaults
    ArtistProfile.objects.all().update(
        sumup_connection_status='not_connected',
        sumup_access_token='',
        sumup_refresh_token='',
        sumup_token_type='',
        sumup_expires_at=None,
        sumup_scope='',
        sumup_merchant_code='',
        sumup_connected_at=None
    )
    print("✅ Reversed SumUp OAuth migration - all artists reset to not_connected")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_sumup_oauth_fields'),
    ]

    operations = [
        migrations.RunPython(
            migrate_existing_artists_to_sumup_workflow,
            reverse_migration
        ),
    ]
