# Generated by Django 5.0.2 on 2025-09-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_username_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
