# Generated by Django 5.2.5 on 2025-09-02 18:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('plan_type', models.CharField(choices=[('basic', 'Basic'), ('professional', 'Professional'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='basic', max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('max_artworks', models.IntegerField(default=10, help_text='Maximum number of artworks artist can list')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Platform commission percentage on sales', max_digits=5)),
                ('featured_artworks', models.IntegerField(default=0, help_text='Number of featured artwork slots')),
                ('features', models.JSONField(default=dict, help_text='Plan features as key-value pairs')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('trial_days', models.IntegerField(default=0, help_text='Free trial period in days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('trialing', 'In Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('paused', 'Paused'), ('expired', 'Expired')], default='trialing', max_length=20)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('trial_start', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Override plan price for this subscription', max_digits=10, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('payment_failed_count', models.IntegerField(default=0)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('last_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('artworks_count', models.IntegerField(default=0)),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_commission_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(limit_choices_to={'user_type': 'artist'}, on_delete=django.db.models.deletion.CASCADE, related_name='artist_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='draft', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('payment_due_date', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('sumup_payment_id', models.CharField(blank=True, max_length=255)),
                ('sumup_response', models.JSONField(blank=True, null=True)),
                ('description', models.TextField()),
                ('line_items', models.JSONField(default=dict, help_text='Detailed breakdown of charges')),
                ('is_refunded', models.BooleanField(default=False)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('upgrade', 'Upgrade'), ('downgrade', 'Downgrade'), ('renewal', 'Renewal'), ('cancellation', 'Cancellation'), ('reactivation', 'Reactivation'), ('pause', 'Pause'), ('resume', 'Resume')], max_length=20)),
                ('from_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('to_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('reason', models.TextField(blank=True)),
                ('effective_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_changes_made', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='subscriptions.subscription')),
                ('from_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_from', to='subscriptions.subscriptionplan')),
                ('to_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_to', to='subscriptions.subscriptionplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('artworks_added', models.IntegerField(default=0)),
                ('artworks_sold', models.IntegerField(default=0)),
                ('total_views', models.IntegerField(default=0)),
                ('total_sales_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('commission_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('featured_artwork_days', models.IntegerField(default=0)),
                ('api_calls', models.IntegerField(default=0)),
                ('storage_used_mb', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('subscription', 'month')},
            },
        ),
    ]
