# Generated by Django 5.0.2 on 2025-09-08 17:05

import django.db.models.deletion
import subscriptions.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={},
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="artist",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="artworks_count",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="auto_renew",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="cancel_at_period_end",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="cancellation_reason",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="payment_failed_count",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="plan",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="price_override",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="subscription_id",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="total_commission_paid",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="total_sales",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="trial_start",
        ),
        migrations.AddField(
            model_name="subscription",
            name="currency",
            field=models.CharField(default="GBP", max_length=3),
        ),
        migrations.AddField(
            model_name="subscription",
            name="monthly_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("15.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="payment_method",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="subscription",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="current_period_end",
            field=models.DateTimeField(
                default=subscriptions.models.Subscription.default_period_end
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="current_period_start",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="next_billing_date",
            field=models.DateTimeField(
                default=subscriptions.models.Subscription.default_period_end
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("trialing", "Trial Period"),
                    ("active", "Active"),
                    ("past_due", "Past Due"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                ],
                default="trialing",
                max_length=20,
            ),
        ),
        migrations.AlterModelTable(
            name="subscription",
            table="subscriptions",
        ),
        migrations.CreateModel(
            name="SubscriptionPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="GBP", max_length=3)),
                ("status", models.CharField(max_length=20)),
                ("transaction_id", models.CharField(blank=True, max_length=255)),
                ("failure_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
