# Generated by Django 5.0.2 on 2025-10-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_notes',
            field=models.TextField(blank=True, help_text='Internal notes about payment verification issues'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('pending_verification', 'Pending Payment Verification'), ('processing', 'Processing'), ('completed', 'Completed'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('failed', 'Payment Failed'), ('expired', 'Verification Expired'), ('requires_manual_review', 'Requires Manual Review'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=30),
        ),
    ]
