# Generated by Django 5.0.2 on 2025-10-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_notes_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='acceptance_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of customer when T&C accepted (for legal records)', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='terms_accepted',
            field=models.BooleanField(default=False, help_text='Customer accepted Terms & Conditions at checkout'),
        ),
        migrations.AddField(
            model_name='order',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When T&C were accepted', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='terms_version',
            field=models.CharField(blank=True, help_text="Version of T&C accepted (e.g., '1.0', '2024-01-15')", max_length=20),
        ),
    ]
